### ISSUE TITLE
LWP/Simple.pm is missing

### ISSUE THREAD

**Issue by tthye1** [RVanDamme/MUFFIN#14]
Hello ,

I got the following error message when trying to run the test files with a conda environment. 
It appears that the LWP/Simple.pm module is missing in the perl distribution of the conda environment. I have locally installed LWP/Simple.pm but this doesn't help. 

Best,

Thorsten 

Creating Conda env: bioconda::samtools=1.10 bioconda::concoct=1.1.0 [cache /media/sdb/NGS/software/MUFFIN/work/conda/env-b73d2eff1d57cdfbb00eefa07d0a371d]
Error executing process > 'maxbin2 (1)'

Caused by:
  Process `maxbin2 (1)` terminated with an error exit status (2)

Command executed:

  run_MaxBin.pl -contig assembly.fasta  -reads subset_R1_clean.fastq -reads2 subset_R2_clean.fastq -reads3 subset_all.fastq  -out maxbin2 -thread 12
  mkdir maxbin_bin
  mv maxbin2.*.fasta maxbin_bin/

Command exit status:
  2

Command output:
  (empty)

Command error:
  Can't locate LWP/Simple.pm in @INC (you may need to install the LWP::Simple module) (@INC contains: /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /media/sdb/NGS/virome/virmap/bbmap /media/sdb/NGS/software/vt /media/sdb/NGS/software/pplacer-Linux-v1.1.alpha17 /media/sdb/NGS/software/ncbi-blast-2.10.0+/bin /media/sdb/NGS/software/abricate-master/bin /media/sdb/NGS/software/cdhit-master /media/sdb/NGS/software/bedtools2/bin /media/sdb/NGS/software/clamms /media/sdb/NGS/software/root/bin /media/sdb/NGS/software/idba-master/bin /media/sdb/NGS/software/SPAdes-3.13.0-Linux/bin /media/sdb/NGS/projects/virome/MetaVic/prinseq-lite-0.20.4/prinseq-lite.pl /media/sdb/NGS/projects/virome/MetaVic/KronaTools-2.7/scripts /media/sdb/NGS/projects/virome/MetaVic/quast-5.0.2 /media/sdb/NGS/projects/virome/MetaVic/ribopicker-standalone-0.4.3 /media/sdb/NGS/projects/virome/MetaVic/GARM_v0.7.5/lib /media/sdb/NGS/software/MUFFIN/work/conda/env-9688beee8668b9c389c89a26d3c36f2c/lib/site_perl/5.30.3/x86_64-linux-thread-multi /media/sdb/NGS/software/MUFFIN/work/conda/env-9688beee8668b9c389c89a26d3c36f2c/lib/site_perl/5.30.3 /media/sdb/NGS/software/MUFFIN/work/conda/env-9688beee8668b9c389c89a26d3c36f2c/lib/5.30.3/x86_64-linux-thread-multi /media/sdb/NGS/software/MUFFIN/work/conda/env-9688beee8668b9c389c89a26d3c36f2c/lib/5.30.3 .) at /media/sdb/NGS/software/MUFFIN/work/conda/env-9688beee8668b9c389c89a26d3c36f2c/bin/run_MaxBin.pl line 4.
  BEGIN failed--compilation aborted at /media/sdb/NGS/software/MUFFIN/work/conda/env-9688beee8668b9c389c89a26d3c36f2c/bin/run_MaxBin.pl line 4.

Work dir:
  /media/sdb/NGS/software/MUFFIN/work/a1/773a3b9ee557c185fca72eb1815029

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

**Comment by RVanDamme** [comment]
Hello,
I apologize for the wait

It seems there is an issue with the conda environment (/work/conda/env-9688beee8668b9c389c89a26d3c36f2c)
I would suggest you to delete it first and rerun the same command, that should solve the issue.

Now for why the error occured, it's probably due to an unexpected interuption during the installation of the conda environment . An error of another process that killed the pipeline and stopped the installation in mid action is probably the cause.

Another error could result of this during the new installation. 
If the environment was downloading the needed perl archive, the said archive might got corrupted and thus the new reinstallation will fail. If this occur you will have in your nextflow.log an error like the following:
`Caused by:
  Failed to create Conda environment
  command: conda create --mkdir --yes --quiet --prefix /work/conda/env-NUMBER.... conda::package
  status : 1
  message:
    InvalidArchiveError("Error with archive /path/to/archive")`
a simple deletion of the archive should fix it for good (if no other archive got corrupted).

All those are tied to the way conda behave, unfortunately it's not something I can prevent during the pipeline, except by reducing the initial errors that can occur that will corrupt conda.
If you still have the cause of the initial interruption of the pipeline, I can look at it and solve it.
I will just need the nextflow.log and also the .command files in the work dir of the process that had the issue.

**Comment by RVanDamme** [comment]
Hello,
Through issue solving and development I crossed again the issue:
Can't locate LWP/Simple.pm in @inc 

It got solved in my latest commit, so you can git pull or wait for the next release and everything should be operational

Best
Renaud
